POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "postman is good at testing backend",
    "important": true,
    "userId": "6828c71d9119e5493e8f7a41"
}

###
GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/6820d76161bc4fa993a1b104