POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "nickleex",
  "name": "Nick",
  "password": "test_password"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "helloworld"
}