POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "nickleex",
  "password": "test_password"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "nickleex",
  "password": "wrongpassword"
}